name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Get tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Get name
        id: name
        run: echo ::set-output name=NAME::$(echo $GITHUB_REF | awk -F / '{print $3}')
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          release_name: "${{ steps.name.outputs.NAME }} ${{ steps.tag.outputs.VERSION }}"
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          asset_name: "${{ steps.name.outputs.NAME }}-${{ steps.tag.outputs.VERSION }}.zip"
          asset_content_type: application/zip
